[versions]

kotlin = "1.6.10"
activity = "1.5.0-alpha01"
androidGradle = "7.1.2"
kotlinxSerialization = "1.3.1"
coroutines = "1.6.0-native-mt"
koin = "3.1.5"
decompose = "0.5.1"
mviKotlin = "3.0.0-beta01"
compose = "1.2.0-alpha02"
reaktive = "1.2.1"
navigation = "2.4.1"
apollo = "3.2.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

android-gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }

decompose-decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extension-compose = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decompose" }

badoo-reaktive = { module = "com.badoo.reaktive:reaktive", version.ref = "reaktive"}

mviKotlin-mviKotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mviKotlin" }
mviKotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mviKotlin" }
mviKotlin-extensionCoroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mviKotlin" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose"}
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose"}
compose-material = { module = "androidx.compose.material:material", version.ref = "compose"}
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose"}
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }

[bundles]

mviKotlin = [
    "mviKotlin-mviKotlin",
    "mviKotlin-main",
    "mviKotlin-extensionCoroutines"
]

compose = [
     "compose-ui",
     "compose-foundation",
     "compose-material",
     "compose-runtime",
     "compose-navigation"
]